# 'version' больше не требуется в современных версиях Docker Compose
services:
  bot:
    build: .
    command: gunicorn --bind 0.0.0.0:8080 src.main:app
    # Используем env_file для загрузки всех переменных из файла .env
    # Это безопаснее, чем прописывать их прямо здесь
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      # Монтируем код для удобной разработки
      - .:/app
    networks:
      - botnet
    # depends_on гарантирует, что db запустится раньше бота
    depends_on:
      - db

  db:
    # Рекомендуется использовать более стабильную версию, например, 16
    image: postgres:17
    restart: always
    # Сервис 'db' должен содержать только переменные для самой базы данных.
    # Они будут взяты из файла .env, как и для сервиса bot.
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      # Пробрасываем порт 5432 контейнера на 5433 хоста
      - "5433:5432"
    volumes:
      # Используем named volume для сохранения данных
      - pgdata:/var/lib/postgresql/data
    networks:
      - botnet

networks:
  botnet:

volumes:
  pgdata:
