services:
  bot:
    build: .
    command: gunicorn --worker-class gevent -b 0.0.0.0:8080 src.main:app
    env_file: .env
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - botnet

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1765362
      POSTGRES_DB: tracking_train
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - botnet

networks:
  botnet:

volumes:
  pgdata:
